#ifndef CONSTANTES_H
#define CONSTANTES_H

#define TOTAL_BARCOS 6
#define TOTAL_REGATAS 3
#define TOTAL_BARCOS_POR_REGATA 4
#define TOTAL_PARTICIPANTES (TOTAL_BARCOS_POR_REGATA*TOTAL_REGATAS)

#endif // CONSTANTES_H